version: "3.9"

volumes:
  FilmesDb:

networks:
  mysqlNET:
  filmeAPINET: 

services:
  mysql:
    image: "mysql:8.0"
    container_name: mysqlDb
    ports: 
      - "3306:3306"
    volumes:
      - FilmesDb:/var/lib/mysql
    environment: 
      - MYSQL_USER=root 
      - MYSQL_PASSWORD=root 
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_ROOT_HOST=% 
      - bind-address:0.0.0.0 
    networks:
      - mysqlNET

  filmeApi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filmeAPI
    networks:
      - mysqlNET
      - filmeAPINET
    ports:
      - 5000:80
    environment:
      - DBHost=mysql
    depends_on:
      - mysql
      